title: Winder's Grid
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8422939
  brandStrength: 0.3879760038107634
  lightness: 0.327957
  brandColors:
    - '#F7C42B'
    - '#FAFCB0'
    - '#073130'
    - '#994634'
    - '#97D1A7'
  rhythmicContrast: 0.765233
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Winder Chen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7777778
layout_spectrum: 0.718638
