name: Winderchen
favicon: null
layout_spectrum: 0.93856
typography_spectrum: 0.56826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.38797600381076336
  lightness: 0.21118401270359755
  saturation: 0.4375
  rhythmicContrast: 0.29214443266391754
purpose: []
