name: Winder Chen
favicon: null
layout_spectrum: 0.93856
typography_spectrum: 0.56826
title: Winder's Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#312926'
    - '#ce6e3b'
    - '#ff3b3b'
    - '#ffb686'
  brandStrength: 0.38797600381076336
  lightness: 0.21118401270359755
  saturation: 0.4375
  rhythmicContrast: 0.29214443266391754
purpose: []
